### ISSUE TITLE
To-Do for api_v2

### ISSUE THREAD

**Issue by zenodallavalle** [zenodallavalle/expenditures-tracer-api#1]
- [x] create api_v2 url endpoint
- [x] create api_v2 serializers, views, permissions, etc.
- [x] edit user view
- [x] include category in database representation
- [x] include cash in database representation
- [x] include expenditures (divided per category divided in expected and actual) in database representation
- [x] allow and handle only update, patch, delete, options and head for `/categories/`
- [x] allow and handle only update, patch, delete, options and head for `/cash/`
- [x] allow and handle update, patch, delete, options and head for `/expenditures/` but also retrieve (this because if you link an expenditure with an expected of a month ago, then you'll have to retrieve it via `/expenditures/<exp_id>/`
- [x] include (light) databases representations in userì
- [x] include the updated database representation in response from CRUD operations in dbs, categories, cash, expenditures
- [x] include prospect of the month in database representation
- [x] include months in the database representation
- [x] make database representation specific per month
